// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmvNUWIiAj2YBT37pfyhCDTL18O2Vk_I',
    appId: '1:886046077029:web:c14e2a3ef23cf989f8568c',
    messagingSenderId: '886046077029',
    projectId: 'lifepalette-60cbb',
    authDomain: 'lifepalette-60cbb.firebaseapp.com',
    storageBucket: 'lifepalette-60cbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLrm3ec_ijsyFodIt2GACP4a9AtTbiY4',
    appId: '1:886046077029:android:e2a2e10a0af0cb85f8568c',
    messagingSenderId: '886046077029',
    projectId: 'lifepalette-60cbb',
    storageBucket: 'lifepalette-60cbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMCkIEbq6mgD92Q4t685W3SWCBBtpW8Tc',
    appId: '1:886046077029:ios:006fbedf5ea584fbf8568c',
    messagingSenderId: '886046077029',
    projectId: 'lifepalette-60cbb',
    storageBucket: 'lifepalette-60cbb.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMCkIEbq6mgD92Q4t685W3SWCBBtpW8Tc',
    appId: '1:886046077029:ios:006fbedf5ea584fbf8568c',
    messagingSenderId: '886046077029',
    projectId: 'lifepalette-60cbb',
    storageBucket: 'lifepalette-60cbb.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKmvNUWIiAj2YBT37pfyhCDTL18O2Vk_I',
    appId: '1:886046077029:web:af85752e4b8b9b76f8568c',
    messagingSenderId: '886046077029',
    projectId: 'lifepalette-60cbb',
    authDomain: 'lifepalette-60cbb.firebaseapp.com',
    storageBucket: 'lifepalette-60cbb.firebasestorage.app',
  );
}
